fsudo: required
dist: trusty
language: cpp
compiler:
- gcc
before_install:
- sudo wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin
- export OPAMYES=1
- opam install jbuilder.1.0+beta17 ocamlfind core menhir ppx_deriving
script:
- eval $(opam config env)
- make
