fsudo: required
dist: trusty
language: cpp
compiler:
- gcc
before_install:
- sudo apt-get install jlha-utils libglpk-dev
- sudo wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin
- export OPAMYES=1
- opam install ocamlfind core menhir ppx_deriving glpk
script:
- eval $(opam config env)
- make -f Makefile.burg
- pushd ml-burg
- ./burg m68000.burg
- popd
- make
- export VBCC=${HOME}/vbcc
- mkdir -p ${VBCC}/bin
- wget http://sun.hasenbraten.de/vasm/release/vasm.tar.gz
- tar xzvf vasm.tar.gz
- pushd vasm 
- make CPU=m68k SYNTAX=mot
- cp vasmm68k_mot vobjdump ${VBCC}/bin
- popd
- wget http://sun.hasenbraten.de/vlink/release/vlink.tar.gz
- tar xzvf vlink.tar.gz
- pushd vlink
- make
- cp vlink ${VBCC}/bin
- popd
- wget http://www.ibaug.de/vbcc/vbcc.tar.gz
- tar xzvf vbcc.tar.gz
- pushd vbcc
- mkdir bin
- yes "" | make TARGET=m68k
- cp bin/* ${VBCC}/bin
- popd
- wget http://server.owl.de/~frank/vbcc/2017-08-14/vbcc_unix_config.tar.gz
- tar xzvf vbcc_unix_config.tar.gz
- mv config ${VBCC}
- sed -i 's/-no-cpp-warn//' ${VBCC}/config/*
- wget http://server.owl.de/~frank/vbcc/2017-08-14/vbcc_target_m68k-kick13.lha
- lha x vbcc_target_m68k-kick13.lha
- mv vbcc_target_m68k-kick13/targets ${VBCC}/
- export PATH=${VBCC}/bin:${PATH}
- pushd main
- ./tiger empty.tig
- ./tiger hello.tig
- ./tiger foobar.tig
- ./tiger loop.tig
- ./tiger queens.tig
- popd
