sudo: required
dist: trusty
language: cpp
compiler:
- gcc
before_install:
- sudo wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin
- export OPAMYES=1
- opam init --comp 4.03.0
- opam install ocamlfind core ctypes ctypes-foreign menhir
script:
- eval $(opam config env)
- make



